import { CategoryQuestions, Question } from './index';

const cppQuestions: CategoryQuestions = {
  basic: {
    1: [
      { type: 'mcq', question: 'Which header is needed for cout?', options: ['<stdio.h>', '<iostream>', '<string>', '<cmath>'], correct: 1 },
      { type: 'mcq', question: 'What is the entry point of a C++ program?', options: ['start()', 'main()', 'init()', 'run()'], correct: 1 },
      { type: 'mcq', question: 'Which keyword declares a variable in C++?', options: ['var', 'let', 'int (or other type)', 'define'], correct: 2 },
      { type: 'mcq', question: 'What does "using namespace std;" do?', options: ['Imports a library', 'Avoids writing std:: prefix', 'Creates a namespace', 'Defines a macro'], correct: 1 },
      { type: 'short', question: 'What operator is used for output in C++?', answer: '<<' },
      { type: 'short', question: 'What is the file extension for C++ source files?', answer: '.cpp' },
      { type: 'short', question: 'What does endl do?', answer: 'newline' },
    ] as Question[],
    2: [
      { type: 'mcq', question: 'Which type stores decimal numbers?', options: ['int', 'char', 'double', 'bool'], correct: 2 },
      { type: 'mcq', question: 'What is the size of int typically?', options: ['1 byte', '2 bytes', '4 bytes', '8 bytes'], correct: 2 },
      { type: 'mcq', question: 'What does "auto" keyword do in C++11?', options: ['Creates auto variable', 'Deduces type automatically', 'Makes constant', 'Allocates memory'], correct: 1 },
      { type: 'mcq', question: 'What is a char in C++?', options: ['A string', 'A single character', 'An integer', 'A boolean'], correct: 1 },
      { type: 'short', question: 'What type stores true/false values?', answer: 'bool' },
      { type: 'short', question: 'What keyword makes a variable constant?', answer: 'const' },
      { type: 'short', question: 'What type stores a single character?', answer: 'char' },
    ] as Question[],
    3: [
      { type: 'mcq', question: 'What does the ++ operator do?', options: ['Adds two numbers', 'Increments by 1', 'Doubles value', 'Compares values'], correct: 1 },
      { type: 'mcq', question: 'What is the difference between ++i and i++?', options: ['No difference', 'Pre vs post increment', 'One is invalid', 'Speed difference'], correct: 1 },
      { type: 'mcq', question: 'What does the && operator represent?', options: ['Bitwise AND', 'Logical AND', 'Address of', 'Reference'], correct: 1 },
      { type: 'mcq', question: 'What is the ternary operator syntax?', options: ['if/else', 'condition ? a : b', 'switch', 'for'], correct: 1 },
      { type: 'short', question: 'What operator gives the remainder of division?', answer: '%' },
      { type: 'short', question: 'What does != mean?', answer: 'not equal' },
      { type: 'short', question: 'What operator is used for logical OR?', answer: '||' },
    ] as Question[],
    4: [
      { type: 'mcq', question: 'How are arrays declared in C++?', options: ['array x[5]', 'int x[5]', 'x = [5]', 'new int(5)'], correct: 1 },
      { type: 'mcq', question: 'What is the index of the first element in an array?', options: ['1', '0', '-1', 'Depends'], correct: 1 },
      { type: 'mcq', question: 'Can C++ arrays change size after creation?', options: ['Yes', 'No', 'Only with resize()', 'Only dynamic arrays'], correct: 1 },
      { type: 'mcq', question: 'What happens if you access an out-of-bounds index?', options: ['Returns 0', 'Undefined behavior', 'Throws exception', 'Returns null'], correct: 1 },
      { type: 'short', question: 'What container is a dynamic array in C++?', answer: 'vector' },
      { type: 'short', question: 'How many elements does int arr[5] hold?', answer: '5' },
      { type: 'short', question: 'What function returns array size for std::array?', answer: 'size' },
    ] as Question[],
    5: [
      { type: 'mcq', question: 'Which header provides std::string?', options: ['<cstring>', '<string>', '<iostream>', '<text>'], correct: 1 },
      { type: 'mcq', question: 'How do you concatenate strings in C++?', options: ['concat()', '+ operator', 'append only', '& operator'], correct: 1 },
      { type: 'mcq', question: 'What does string::length() return?', options: ['Memory size', 'Number of characters', 'Buffer size', 'Max capacity'], correct: 1 },
      { type: 'mcq', question: 'What is a C-string?', options: ['A std::string', 'A null-terminated char array', 'A wide string', 'A unicode string'], correct: 1 },
      { type: 'short', question: 'What character terminates a C-string?', answer: '\\0' },
      { type: 'short', question: 'What method finds a substring in std::string?', answer: 'find' },
      { type: 'short', question: 'What method extracts part of a string?', answer: 'substr' },
    ] as Question[],
    6: [
      { type: 'mcq', question: 'What is a pointer?', options: ['A variable', 'A variable storing a memory address', 'A function', 'A constant'], correct: 1 },
      { type: 'mcq', question: 'What operator gets the address of a variable?', options: ['*', '&', '->', '::'], correct: 1 },
      { type: 'mcq', question: 'What operator dereferences a pointer?', options: ['&', '*', '->', '.'], correct: 1 },
      { type: 'mcq', question: 'What is a null pointer?', options: ['An error', 'A pointer pointing to nothing', 'A dangling pointer', 'A void pointer'], correct: 1 },
      { type: 'short', question: 'What keyword represents a null pointer in C++11?', answer: 'nullptr' },
      { type: 'short', question: 'What type can point to any data type?', answer: 'void' },
      { type: 'short', question: 'What is pointer arithmetic?', answer: 'math' },
    ] as Question[],
    7: [
      { type: 'mcq', question: 'What is a reference in C++?', options: ['A copy', 'An alias for a variable', 'A pointer', 'A constant'], correct: 1 },
      { type: 'mcq', question: 'Can a reference be null?', options: ['Yes', 'No', 'Only in C++11', 'Depends on type'], correct: 1 },
      { type: 'mcq', question: 'Can you reassign a reference?', options: ['Yes', 'No', 'Only with const_cast', 'Only to same type'], correct: 1 },
      { type: 'mcq', question: 'What is the advantage of pass-by-reference?', options: ['Creates copy', 'Avoids copying large objects', 'Slower', 'Uses more memory'], correct: 1 },
      { type: 'short', question: 'What symbol declares a reference?', answer: '&' },
      { type: 'short', question: 'Must a reference be initialized when declared?', answer: 'yes' },
      { type: 'short', question: 'What is an rvalue reference symbol?', answer: '&&' },
    ] as Question[],
  },
  intermediate: {
    1: [
      { type: 'mcq', question: 'What is function overloading?', options: ['Calling recursively', 'Same name with different parameters', 'Default parameters', 'Inline functions'], correct: 1 },
      { type: 'mcq', question: 'What does the "inline" keyword suggest?', options: ['Make global', 'Replace call with function body', 'Make static', 'Make virtual'], correct: 1 },
      { type: 'mcq', question: 'What is a default parameter?', options: ['First parameter', 'Parameter with preset value', 'Required parameter', 'Void parameter'], correct: 1 },
      { type: 'mcq', question: 'What is recursion?', options: ['A loop', 'A function calling itself', 'An error', 'A macro'], correct: 1 },
      { type: 'short', question: 'What does a void function return?', answer: 'nothing' },
      { type: 'short', question: 'What is the keyword to define a function prototype?', answer: 'declaration' },
      { type: 'short', question: 'Where are default parameters placed?', answer: 'end' },
    ] as Question[],
    2: [
      { type: 'mcq', question: 'What is a class in C++?', options: ['A function', 'A blueprint for objects', 'A variable', 'A namespace'], correct: 1 },
      { type: 'mcq', question: 'What is the default access specifier for class members?', options: ['public', 'private', 'protected', 'friend'], correct: 1 },
      { type: 'mcq', question: 'What is a constructor?', options: ['A destructor', 'A method called when object is created', 'A static method', 'A virtual method'], correct: 1 },
      { type: 'mcq', question: 'What is a destructor?', options: ['Creates objects', 'Cleans up when object is destroyed', 'Copies objects', 'Initializes members'], correct: 1 },
      { type: 'short', question: 'What symbol prefixes a destructor name?', answer: '~' },
      { type: 'short', question: 'What keyword makes members accessible from outside?', answer: 'public' },
      { type: 'short', question: 'What operator accesses members through a pointer?', answer: '->' },
    ] as Question[],
    3: [
      { type: 'mcq', question: 'What keyword is used for inheritance?', options: ['extends', 'inherits', ':', 'implements'], correct: 2 },
      { type: 'mcq', question: 'What is public inheritance?', options: ['All become public', 'Public stays public', 'All become private', 'No access change'], correct: 1 },
      { type: 'mcq', question: 'Can C++ do multiple inheritance?', options: ['No', 'Yes', 'Only single', 'Only with interfaces'], correct: 1 },
      { type: 'mcq', question: 'What is the diamond problem?', options: ['A syntax error', 'Ambiguity in multiple inheritance', 'A memory leak', 'A design pattern'], correct: 1 },
      { type: 'short', question: 'What access specifier allows derived class access only?', answer: 'protected' },
      { type: 'short', question: 'What keyword resolves the diamond problem?', answer: 'virtual' },
      { type: 'short', question: 'What is the base class called in inheritance?', answer: 'parent' },
    ] as Question[],
    4: [
      { type: 'mcq', question: 'What is polymorphism?', options: ['One form', 'Many forms', 'No form', 'Abstract form'], correct: 1 },
      { type: 'mcq', question: 'What keyword enables runtime polymorphism?', options: ['static', 'virtual', 'override', 'abstract'], correct: 1 },
      { type: 'mcq', question: 'What is a pure virtual function?', options: ['A defined function', 'A function with = 0', 'A static function', 'A friend function'], correct: 1 },
      { type: 'mcq', question: 'What is an abstract class?', options: ['A normal class', 'A class with at least one pure virtual function', 'A template class', 'A final class'], correct: 1 },
      { type: 'short', question: 'What is compile-time polymorphism called?', answer: 'overloading' },
      { type: 'short', question: 'What is runtime polymorphism called?', answer: 'overriding' },
      { type: 'short', question: 'Can you instantiate an abstract class?', answer: 'no' },
    ] as Question[],
    5: [
      { type: 'mcq', question: 'What are templates?', options: ['Macros', 'Generic programming constructs', 'Classes', 'Functions'], correct: 1 },
      { type: 'mcq', question: 'What keyword defines a template?', options: ['generic', 'template', 'typename', 'class'], correct: 1 },
      { type: 'mcq', question: 'Can templates work with both functions and classes?', options: ['Only functions', 'Only classes', 'Both', 'Neither'], correct: 2 },
      { type: 'mcq', question: 'When are templates instantiated?', options: ['At runtime', 'At compile time', 'At link time', 'Never'], correct: 1 },
      { type: 'short', question: 'What keyword can replace "class" in template parameter?', answer: 'typename' },
      { type: 'short', question: 'Can templates have default type parameters?', answer: 'yes' },
      { type: 'short', question: 'What is template specialization?', answer: 'customization' },
    ] as Question[],
    6: [
      { type: 'mcq', question: 'What does STL stand for?', options: ['Standard Type Library', 'Standard Template Library', 'System Template Library', 'Standard Test Library'], correct: 1 },
      { type: 'mcq', question: 'Which container provides key-value storage?', options: ['vector', 'set', 'map', 'list'], correct: 2 },
      { type: 'mcq', question: 'What does std::sort require?', options: ['A list', 'Random access iterators', 'A map', 'A stack'], correct: 1 },
      { type: 'mcq', question: 'What is an iterator?', options: ['A pointer', 'An object to traverse containers', 'A function', 'A template'], correct: 1 },
      { type: 'short', question: 'What container is a LIFO structure?', answer: 'stack' },
      { type: 'short', question: 'What container is a FIFO structure?', answer: 'queue' },
      { type: 'short', question: 'What header provides std::vector?', answer: '<vector>' },
    ] as Question[],
    7: [
      { type: 'mcq', question: 'Which class handles file input?', options: ['ofstream', 'ifstream', 'fstream', 'iostream'], correct: 1 },
      { type: 'mcq', question: 'What mode opens a file for appending?', options: ['ios::in', 'ios::out', 'ios::app', 'ios::trunc'], correct: 2 },
      { type: 'mcq', question: 'What method checks if file is open?', options: ['exists()', 'is_open()', 'opened()', 'check()'], correct: 1 },
      { type: 'mcq', question: 'What does getline() do?', options: ['Writes a line', 'Reads a full line', 'Counts lines', 'Deletes a line'], correct: 1 },
      { type: 'short', question: 'What header is needed for file I/O?', answer: '<fstream>' },
      { type: 'short', question: 'What method closes a file?', answer: 'close' },
      { type: 'short', question: 'What class handles both file input and output?', answer: 'fstream' },
    ] as Question[],
  },
  advanced: {
    1: [
      { type: 'mcq', question: 'What is a unique_ptr?', options: ['Shared ownership', 'Exclusive ownership smart pointer', 'Raw pointer', 'Weak reference'], correct: 1 },
      { type: 'mcq', question: 'What does shared_ptr use for memory management?', options: ['Garbage collection', 'Reference counting', 'Manual delete', 'Stack allocation'], correct: 1 },
      { type: 'mcq', question: 'What is weak_ptr used for?', options: ['Strong ownership', 'Breaking circular references', 'Manual memory', 'Array management'], correct: 1 },
      { type: 'mcq', question: 'What function creates a unique_ptr?', options: ['new', 'make_unique', 'make_shared', 'allocate'], correct: 1 },
      { type: 'short', question: 'What header provides smart pointers?', answer: '<memory>' },
      { type: 'short', question: 'Can you copy a unique_ptr?', answer: 'no' },
      { type: 'short', question: 'What function creates a shared_ptr?', answer: 'make_shared' },
    ] as Question[],
    2: [
      { type: 'mcq', question: 'What is move semantics?', options: ['Copying data', 'Transferring resources without copying', 'Deleting data', 'Allocating memory'], correct: 1 },
      { type: 'mcq', question: 'What does std::move() do?', options: ['Moves memory', 'Casts to rvalue reference', 'Copies data', 'Deletes object'], correct: 1 },
      { type: 'mcq', question: 'What is an rvalue reference?', options: ['A normal reference', 'A reference to a temporary', 'A const reference', 'A pointer'], correct: 1 },
      { type: 'mcq', question: 'When is a move constructor called?', options: ['Always', 'When initializing from temporary', 'Never', 'On copy'], correct: 1 },
      { type: 'short', question: 'What symbol denotes an rvalue reference?', answer: '&&' },
      { type: 'short', question: 'Is a moved-from object valid?', answer: 'yes' },
      { type: 'short', question: 'What is perfect forwarding?', answer: 'forwarding' },
    ] as Question[],
    3: [
      { type: 'mcq', question: 'Which header provides std::thread?', options: ['<process>', '<thread>', '<async>', '<parallel>'], correct: 1 },
      { type: 'mcq', question: 'What does std::mutex do?', options: ['Creates threads', 'Provides mutual exclusion', 'Sends signals', 'Manages memory'], correct: 1 },
      { type: 'mcq', question: 'What is a race condition?', options: ['Fast code', 'Concurrent access causing bugs', 'A deadlock', 'An optimization'], correct: 1 },
      { type: 'mcq', question: 'What does std::lock_guard provide?', options: ['Manual locking', 'RAII mutex locking', 'Thread creation', 'Async execution'], correct: 1 },
      { type: 'short', question: 'What method waits for a thread to finish?', answer: 'join' },
      { type: 'short', question: 'What makes a variable safe across threads?', answer: 'atomic' },
      { type: 'short', question: 'What is a deadlock?', answer: 'circular' },
    ] as Question[],
    4: [
      { type: 'mcq', question: 'What is a lambda expression?', options: ['A named function', 'An anonymous function object', 'A macro', 'A template'], correct: 1 },
      { type: 'mcq', question: 'What does [=] capture?', options: ['Nothing', 'All by value', 'All by reference', 'Only this'], correct: 1 },
      { type: 'mcq', question: 'What does [&] capture?', options: ['Nothing', 'All by value', 'All by reference', 'Only this'], correct: 2 },
      { type: 'mcq', question: 'Can lambdas be stored in std::function?', options: ['No', 'Yes', 'Only simple ones', 'Only with auto'], correct: 1 },
      { type: 'short', question: 'What brackets start a lambda\'s capture list?', answer: '[]' },
      { type: 'short', question: 'What keyword makes a lambda body modifiable?', answer: 'mutable' },
      { type: 'short', question: 'Can lambdas be generic in C++14?', answer: 'yes' },
    ] as Question[],
    5: [
      { type: 'mcq', question: 'What is template metaprogramming?', options: ['Runtime computation', 'Compile-time computation with templates', 'A design pattern', 'Dynamic typing'], correct: 1 },
      { type: 'mcq', question: 'What is SFINAE?', options: ['An error', 'Substitution Failure Is Not An Error', 'A compiler', 'A library'], correct: 1 },
      { type: 'mcq', question: 'What are type traits?', options: ['Variables', 'Compile-time type information', 'Runtime checks', 'Macros'], correct: 1 },
      { type: 'mcq', question: 'What are C++20 concepts?', options: ['Abstract classes', 'Named constraints on template parameters', 'Interfaces', 'Modules'], correct: 1 },
      { type: 'short', question: 'What header provides type traits?', answer: '<type_traits>' },
      { type: 'short', question: 'What keyword defines a concept in C++20?', answer: 'concept' },
      { type: 'short', question: 'Are constexpr functions evaluated at compile time?', answer: 'yes' },
    ] as Question[],
    6: [
      { type: 'mcq', question: 'What is RAII?', options: ['A design pattern', 'Resource Acquisition Is Initialization', 'A memory model', 'A compiler feature'], correct: 1 },
      { type: 'mcq', question: 'What does "new" do?', options: ['Creates on stack', 'Allocates on heap', 'Creates reference', 'Copies object'], correct: 1 },
      { type: 'mcq', question: 'What does "delete" do?', options: ['Removes file', 'Frees heap memory', 'Clears stack', 'Removes variable'], correct: 1 },
      { type: 'mcq', question: 'What is a memory leak?', options: ['Fast memory', 'Unreleased allocated memory', 'Stack overflow', 'Segfault'], correct: 1 },
      { type: 'short', question: 'What tool detects memory leaks?', answer: 'valgrind' },
      { type: 'short', question: 'What is stack vs heap allocation difference?', answer: 'automatic' },
      { type: 'short', question: 'What does delete[] free?', answer: 'array' },
    ] as Question[],
    7: [
      { type: 'mcq', question: 'What is the Singleton pattern?', options: ['Multiple objects', 'Exactly one instance', 'A factory', 'An observer'], correct: 1 },
      { type: 'mcq', question: 'What does the Factory pattern do?', options: ['Destroys objects', 'Creates objects without specifying exact type', 'Copies objects', 'Sorts objects'], correct: 1 },
      { type: 'mcq', question: 'What is the Strategy pattern?', options: ['One algorithm', 'Family of interchangeable algorithms', 'A sorting method', 'A constructor'], correct: 1 },
      { type: 'mcq', question: 'What is the CRTP?', options: ['A runtime pattern', 'Curiously Recurring Template Pattern', 'A concurrency pattern', 'A memory pattern'], correct: 1 },
      { type: 'short', question: 'What pattern adds responsibilities to objects dynamically?', answer: 'decorator' },
      { type: 'short', question: 'What pattern provides a surrogate for another object?', answer: 'proxy' },
      { type: 'short', question: 'What pattern defines a skeleton algorithm?', answer: 'template' },
    ] as Question[],
  },
};

export default cppQuestions;
