import { CategoryQuestions, Question } from './index';

const javascriptQuestions: CategoryQuestions = {
  basic: {
    1: [
      { type: 'mcq', question: 'Which keyword declares a block-scoped variable?', options: ['var', 'let', 'dim', 'define'], correct: 1 },
      { type: 'mcq', question: 'What is the difference between let and const?', options: ['No difference', 'const cannot be reassigned', 'let is global', 'const is hoisted'], correct: 1 },
      { type: 'mcq', question: 'What does "var" have that "let" does not?', options: ['Block scope', 'Function scope', 'Constant value', 'Type checking'], correct: 1 },
      { type: 'mcq', question: 'Which is the correct way to declare a constant?', options: ['var x = 5', 'let x = 5', 'const x = 5', 'constant x = 5'], correct: 2 },
      { type: 'short', question: 'What keyword declares a variable that cannot be reassigned?', answer: 'const' },
      { type: 'short', question: 'What function logs output to the console?', answer: 'console.log' },
      { type: 'short', question: 'Is JavaScript case-sensitive?', answer: 'yes' },
    ] as Question[],
    2: [
      { type: 'mcq', question: 'What does typeof null return?', options: ['"null"', '"object"', '"undefined"', '"boolean"'], correct: 1 },
      { type: 'mcq', question: 'Which is NOT a primitive data type?', options: ['string', 'number', 'object', 'boolean'], correct: 2 },
      { type: 'mcq', question: 'What is NaN?', options: ['A string', 'Not a Number', 'Null value', 'An error'], correct: 1 },
      { type: 'mcq', question: 'What does typeof undefined return?', options: ['"null"', '"undefined"', '"object"', '"void"'], correct: 1 },
      { type: 'short', question: 'What is the type of NaN?', answer: 'number' },
      { type: 'short', question: 'What value represents intentional absence?', answer: 'null' },
      { type: 'short', question: 'How many primitive types does JavaScript have?', answer: '7' },
    ] as Question[],
    3: [
      { type: 'mcq', question: 'What does === check?', options: ['Value only', 'Type only', 'Value and type', 'Reference'], correct: 2 },
      { type: 'mcq', question: 'What is the result of "5" + 3?', options: ['8', '"53"', 'Error', '53'], correct: 1 },
      { type: 'mcq', question: 'What does the ternary operator look like?', options: ['if/else', '? :', 'switch', '&&'], correct: 1 },
      { type: 'mcq', question: 'What does !! (double negation) do?', options: ['Negates twice', 'Converts to boolean', 'Creates error', 'Checks null'], correct: 1 },
      { type: 'short', question: 'What operator checks strict equality?', answer: '===' },
      { type: 'short', question: 'What is "5" - 3 in JavaScript?', answer: '2' },
      { type: 'short', question: 'What operator returns the remainder?', answer: '%' },
    ] as Question[],
    4: [
      { type: 'mcq', question: 'Which method finds the index of a substring?', options: ['search()', 'indexOf()', 'find()', 'locate()'], correct: 1 },
      { type: 'mcq', question: 'What does template literals use?', options: ['Single quotes', 'Double quotes', 'Backticks', 'Parentheses'], correct: 2 },
      { type: 'mcq', question: 'Which method splits a string into an array?', options: ['split()', 'slice()', 'splice()', 'separate()'], correct: 0 },
      { type: 'mcq', question: 'Are strings mutable in JavaScript?', options: ['Yes', 'No', 'Only with let', 'Only in strict mode'], correct: 1 },
      { type: 'short', question: 'What property returns the length of a string?', answer: 'length' },
      { type: 'short', question: 'What method converts a string to lowercase?', answer: 'toLowerCase' },
      { type: 'short', question: 'What character starts a template literal expression?', answer: '$' },
    ] as Question[],
    5: [
      { type: 'mcq', question: 'Which method adds an element to the end of an array?', options: ['push()', 'append()', 'add()', 'insert()'], correct: 0 },
      { type: 'mcq', question: 'What does array.pop() do?', options: ['Adds to start', 'Removes from end', 'Removes from start', 'Sorts array'], correct: 1 },
      { type: 'mcq', question: 'Which method creates a new array by transforming elements?', options: ['forEach()', 'filter()', 'map()', 'reduce()'], correct: 2 },
      { type: 'mcq', question: 'What does Array.isArray() check?', options: ['If empty', 'If an array', 'Array length', 'Array type'], correct: 1 },
      { type: 'short', question: 'What method removes the first element of an array?', answer: 'shift' },
      { type: 'short', question: 'What method joins array elements into a string?', answer: 'join' },
      { type: 'short', question: 'What property gives the number of elements?', answer: 'length' },
    ] as Question[],
    6: [
      { type: 'mcq', question: 'How do you access an object property?', options: ['obj[key] or obj.key', 'obj->key', 'obj::key', 'obj(key)'], correct: 0 },
      { type: 'mcq', question: 'What does Object.keys() return?', options: ['Values', 'Key-value pairs', 'Array of keys', 'Object copy'], correct: 2 },
      { type: 'mcq', question: 'What is destructuring?', options: ['Deleting an object', 'Extracting values into variables', 'Copying an object', 'Freezing an object'], correct: 1 },
      { type: 'mcq', question: 'What does the spread operator (...) do?', options: ['Deletes properties', 'Copies/spreads elements', 'Creates a class', 'Throws an error'], correct: 1 },
      { type: 'short', question: 'What method returns an array of object values?', answer: 'values' },
      { type: 'short', question: 'What keyword deletes an object property?', answer: 'delete' },
      { type: 'short', question: 'What does JSON stand for?', answer: 'JavaScript' },
    ] as Question[],
    7: [
      { type: 'mcq', question: 'What does document.getElementById() return?', options: ['An array', 'A single element', 'A NodeList', 'A string'], correct: 1 },
      { type: 'mcq', question: 'Which method adds an event listener?', options: ['onClick()', 'addEventListener()', 'addEvent()', 'listen()'], correct: 1 },
      { type: 'mcq', question: 'What does innerHTML do?', options: ['Returns CSS', 'Gets/sets HTML content', 'Creates elements', 'Removes elements'], correct: 1 },
      { type: 'mcq', question: 'What is the DOM?', options: ['A database', 'Document Object Model', 'A framework', 'A protocol'], correct: 1 },
      { type: 'short', question: 'What method selects elements by CSS selector?', answer: 'querySelector' },
      { type: 'short', question: 'What object represents the browser window?', answer: 'window' },
      { type: 'short', question: 'What property changes an element\'s text?', answer: 'textContent' },
    ] as Question[],
  },
  intermediate: {
    1: [
      { type: 'mcq', question: 'What is a function expression?', options: ['A named function', 'A function assigned to a variable', 'A class method', 'An IIFE'], correct: 1 },
      { type: 'mcq', question: 'What is the syntax for an arrow function?', options: ['function =>', '() =>', 'fn()', '-> ()'], correct: 1 },
      { type: 'mcq', question: 'What does "hoisting" mean for functions?', options: ['Functions moved to end', 'Function declarations available before definition', 'Functions are deleted', 'Functions run automatically'], correct: 1 },
      { type: 'mcq', question: 'What is an IIFE?', options: ['A class', 'Immediately Invoked Function Expression', 'A module', 'An interface'], correct: 1 },
      { type: 'short', question: 'What keyword defines a function?', answer: 'function' },
      { type: 'short', question: 'Do arrow functions have their own "this"?', answer: 'no' },
      { type: 'short', question: 'What are functions that take other functions as arguments called?', answer: 'higher-order' },
    ] as Question[],
    2: [
      { type: 'mcq', question: 'What is a closure?', options: ['A loop', 'A function with access to its outer scope', 'A class', 'An error'], correct: 1 },
      { type: 'mcq', question: 'When is a closure created?', options: ['At compile time', 'When a function is defined inside another', 'When an error occurs', 'At page load'], correct: 1 },
      { type: 'mcq', question: 'What does a closure "close over"?', options: ['The DOM', 'Variables from outer scope', 'Global state', 'The event loop'], correct: 1 },
      { type: 'mcq', question: 'Can closures cause memory leaks?', options: ['Never', 'Yes if not managed properly', 'Only in strict mode', 'Only with var'], correct: 1 },
      { type: 'short', question: 'Do closures retain references to outer variables?', answer: 'yes' },
      { type: 'short', question: 'What scope does a closure have access to?', answer: 'lexical' },
      { type: 'short', question: 'Can closures access variables after the outer function returns?', answer: 'yes' },
    ] as Question[],
    3: [
      { type: 'mcq', question: 'What is a callback function?', options: ['A return value', 'A function passed as an argument', 'A global function', 'An event'], correct: 1 },
      { type: 'mcq', question: 'What is "callback hell"?', options: ['An error type', 'Deeply nested callbacks', 'A memory leak', 'A security issue'], correct: 1 },
      { type: 'mcq', question: 'Which method uses a callback to iterate arrays?', options: ['map()', 'forEach()', 'Both A and B', 'Neither'], correct: 2 },
      { type: 'mcq', question: 'Are callbacks synchronous or asynchronous?', options: ['Always sync', 'Always async', 'Can be either', 'Neither'], correct: 2 },
      { type: 'short', question: 'What pattern replaced deeply nested callbacks?', answer: 'promises' },
      { type: 'short', question: 'What function executes a callback after a delay?', answer: 'setTimeout' },
      { type: 'short', question: 'What function calls a callback repeatedly at intervals?', answer: 'setInterval' },
    ] as Question[],
    4: [
      { type: 'mcq', question: 'What states can a Promise be in?', options: ['open/closed', 'pending/fulfilled/rejected', 'true/false', 'sync/async'], correct: 1 },
      { type: 'mcq', question: 'Which method handles a fulfilled Promise?', options: ['catch()', 'then()', 'finally()', 'resolve()'], correct: 1 },
      { type: 'mcq', question: 'What does Promise.all() do?', options: ['Runs one promise', 'Waits for all promises', 'Cancels promises', 'Creates a promise'], correct: 1 },
      { type: 'mcq', question: 'What method handles rejected Promises?', options: ['then()', 'catch()', 'finally()', 'reject()'], correct: 1 },
      { type: 'short', question: 'What method runs regardless of promise outcome?', answer: 'finally' },
      { type: 'short', question: 'What creates a new Promise?', answer: 'new' },
      { type: 'short', question: 'What does Promise.race() return?', answer: 'first' },
    ] as Question[],
    5: [
      { type: 'mcq', question: 'What does the "await" keyword do?', options: ['Creates a promise', 'Pauses execution until promise resolves', 'Throws an error', 'Creates a thread'], correct: 1 },
      { type: 'mcq', question: 'Where can you use "await"?', options: ['Anywhere', 'Inside async functions', 'In loops only', 'In callbacks'], correct: 1 },
      { type: 'mcq', question: 'What does an async function always return?', options: ['undefined', 'A Promise', 'A callback', 'An object'], correct: 1 },
      { type: 'mcq', question: 'How do you handle errors with async/await?', options: ['then/catch', 'try/catch', 'if/else', 'throw/handle'], correct: 1 },
      { type: 'short', question: 'What keyword marks a function as asynchronous?', answer: 'async' },
      { type: 'short', question: 'Can you use await at the top level in modules?', answer: 'yes' },
      { type: 'short', question: 'What does async/await replace syntactically?', answer: 'then' },
    ] as Question[],
    6: [
      { type: 'mcq', question: 'Which keyword defines a class in JavaScript?', options: ['function', 'class', 'object', 'struct'], correct: 1 },
      { type: 'mcq', question: 'What is the constructor method?', options: ['A static method', 'Initializes new instances', 'A getter', 'A destructor'], correct: 1 },
      { type: 'mcq', question: 'How do you create inheritance?', options: ['inherits', 'extends', 'implements', 'includes'], correct: 1 },
      { type: 'mcq', question: 'Are JS classes syntactic sugar over prototypes?', options: ['No', 'Yes', 'Only in ES5', 'Only with Babel'], correct: 1 },
      { type: 'short', question: 'What keyword creates a new instance?', answer: 'new' },
      { type: 'short', question: 'What keyword calls the parent constructor?', answer: 'super' },
      { type: 'short', question: 'Can classes have static methods?', answer: 'yes' },
    ] as Question[],
    7: [
      { type: 'mcq', question: 'What are ES modules?', options: ['A library', 'Native module system using import/export', 'A framework', 'A bundler'], correct: 1 },
      { type: 'mcq', question: 'What is a default export?', options: ['Exports all', 'Exports one main value', 'Exports nothing', 'Exports types'], correct: 1 },
      { type: 'mcq', question: 'What is the difference between named and default exports?', options: ['No difference', 'Named uses curly braces on import', 'Default is faster', 'Named is deprecated'], correct: 1 },
      { type: 'mcq', question: 'What does "import * as" do?', options: ['Imports nothing', 'Imports all named exports as namespace', 'Creates a copy', 'Deletes module'], correct: 1 },
      { type: 'short', question: 'What keyword exports a value from a module?', answer: 'export' },
      { type: 'short', question: 'What keyword imports a module?', answer: 'import' },
      { type: 'short', question: 'What is dynamic import syntax?', answer: 'import()' },
    ] as Question[],
  },
  advanced: {
    1: [
      { type: 'mcq', question: 'What is a prototype in JavaScript?', options: ['A class', 'An object from which others inherit', 'A variable', 'A module'], correct: 1 },
      { type: 'mcq', question: 'What does Object.create() do?', options: ['Copies an object', 'Creates object with specified prototype', 'Deletes an object', 'Freezes an object'], correct: 1 },
      { type: 'mcq', question: 'What is the prototype chain?', options: ['Array of prototypes', 'Linked list of objects for property lookup', 'A design pattern', 'An event system'], correct: 1 },
      { type: 'mcq', question: 'What is __proto__?', options: ['A method', 'Reference to object\'s prototype', 'A constructor', 'A class'], correct: 1 },
      { type: 'short', question: 'What is at the end of every prototype chain?', answer: 'null' },
      { type: 'short', question: 'What method checks if a property is own (not inherited)?', answer: 'hasOwnProperty' },
      { type: 'short', question: 'Are all objects in JS linked to a prototype?', answer: 'yes' },
    ] as Question[],
    2: [
      { type: 'mcq', question: 'What is the event loop?', options: ['A for loop', 'Mechanism that handles async operations', 'A DOM event', 'A timer'], correct: 1 },
      { type: 'mcq', question: 'What is the call stack?', options: ['A queue', 'LIFO structure tracking function execution', 'An array', 'A linked list'], correct: 1 },
      { type: 'mcq', question: 'What is the microtask queue?', options: ['For setTimeout', 'For Promises and queueMicrotask', 'For DOM events', 'For I/O'], correct: 1 },
      { type: 'mcq', question: 'Which has higher priority: microtasks or macrotasks?', options: ['Macrotasks', 'Microtasks', 'Equal', 'Depends on browser'], correct: 1 },
      { type: 'short', question: 'Is JavaScript single-threaded?', answer: 'yes' },
      { type: 'short', question: 'What queue do setTimeout callbacks go to?', answer: 'macrotask' },
      { type: 'short', question: 'What processes async callbacks in JS?', answer: 'event loop' },
    ] as Question[],
    3: [
      { type: 'mcq', question: 'What is the Fetch API?', options: ['A database', 'A modern way to make HTTP requests', 'A CSS feature', 'A testing tool'], correct: 1 },
      { type: 'mcq', question: 'What does fetch() return?', options: ['A string', 'A Promise', 'An object', 'A callback'], correct: 1 },
      { type: 'mcq', question: 'What is a Web Worker?', options: ['A server', 'Background thread for JS', 'A CSS animation', 'A build tool'], correct: 1 },
      { type: 'mcq', question: 'What is localStorage?', options: ['Server storage', 'Client-side key-value storage', 'A database', 'A cookie'], correct: 1 },
      { type: 'short', question: 'What method parses a JSON string?', answer: 'parse' },
      { type: 'short', question: 'What API provides client-side storage with expiration?', answer: 'sessionStorage' },
      { type: 'short', question: 'What does the Cache API cache?', answer: 'responses' },
    ] as Question[],
    4: [
      { type: 'mcq', question: 'What does requestAnimationFrame do?', options: ['Creates animation CSS', 'Schedules callback before next repaint', 'Loads images', 'Plays video'], correct: 1 },
      { type: 'mcq', question: 'What is debouncing?', options: ['Running immediately', 'Delaying execution until pause in calls', 'Canceling events', 'Caching results'], correct: 1 },
      { type: 'mcq', question: 'What is lazy loading?', options: ['Loading everything upfront', 'Deferring load until needed', 'Fast loading', 'Preloading'], correct: 1 },
      { type: 'mcq', question: 'What tool measures JS performance?', options: ['console.log', 'Performance API', 'alert()', 'debugger'], correct: 1 },
      { type: 'short', question: 'What limits function execution rate to once per interval?', answer: 'throttling' },
      { type: 'short', question: 'What technique reuses DOM elements in long lists?', answer: 'virtualization' },
      { type: 'short', question: 'What method measures time between marks?', answer: 'measure' },
    ] as Question[],
    5: [
      { type: 'mcq', question: 'What is unit testing?', options: ['Testing the whole app', 'Testing individual functions', 'Testing the UI', 'Testing performance'], correct: 1 },
      { type: 'mcq', question: 'Which is a popular JS testing framework?', options: ['JUnit', 'Jest', 'PyTest', 'NUnit'], correct: 1 },
      { type: 'mcq', question: 'What is a test assertion?', options: ['A test file', 'A statement that checks expected outcome', 'A mock', 'A fixture'], correct: 1 },
      { type: 'mcq', question: 'What is mocking?', options: ['Deleting tests', 'Simulating dependencies', 'Running tests', 'Writing docs'], correct: 1 },
      { type: 'short', question: 'What function groups related tests in Jest?', answer: 'describe' },
      { type: 'short', question: 'What function defines a test case in Jest?', answer: 'test' },
      { type: 'short', question: 'What does TDD stand for?', answer: 'Test-Driven' },
    ] as Question[],
    6: [
      { type: 'mcq', question: 'What is the Observer pattern?', options: ['Creating objects', 'Subscribing to state changes', 'Sorting data', 'Managing memory'], correct: 1 },
      { type: 'mcq', question: 'What is the Module pattern?', options: ['A loop', 'Encapsulating code with private scope', 'A class', 'An import'], correct: 1 },
      { type: 'mcq', question: 'What does the Singleton pattern ensure?', options: ['Multiple instances', 'Only one instance', 'No instances', 'Lazy loading'], correct: 1 },
      { type: 'mcq', question: 'What is the Pub/Sub pattern?', options: ['Publishing code', 'Decoupled event communication', 'A testing pattern', 'A build pattern'], correct: 1 },
      { type: 'short', question: 'What pattern wraps an object to add behavior?', answer: 'decorator' },
      { type: 'short', question: 'What pattern provides a substitute for another object?', answer: 'proxy' },
      { type: 'short', question: 'What pattern separates object construction from representation?', answer: 'builder' },
    ] as Question[],
    7: [
      { type: 'mcq', question: 'What is TypeScript?', options: ['A new language', 'A typed superset of JavaScript', 'A framework', 'A runtime'], correct: 1 },
      { type: 'mcq', question: 'What does TypeScript compile to?', options: ['Machine code', 'JavaScript', 'WebAssembly', 'Bytecode'], correct: 1 },
      { type: 'mcq', question: 'What is an interface in TypeScript?', options: ['A class', 'A contract for object shape', 'A function', 'A module'], correct: 1 },
      { type: 'mcq', question: 'What are generics in TypeScript?', options: ['Global variables', 'Reusable type-safe components', 'Error handlers', 'Event listeners'], correct: 1 },
      { type: 'short', question: 'What keyword defines a type alias in TypeScript?', answer: 'type' },
      { type: 'short', question: 'What is the TypeScript config file called?', answer: 'tsconfig.json' },
      { type: 'short', question: 'Does TypeScript exist at runtime?', answer: 'no' },
    ] as Question[],
  },
};

export default javascriptQuestions;
