import { CategoryQuestions, MCQ, ShortQuestion, Question } from './index';

const pythonQuestions: CategoryQuestions = {
  basic: {
    1: [
      { type: 'mcq', question: 'Which keyword is used to declare a variable in Python?', options: ['var', 'let', 'No keyword needed', 'dim'], correct: 2 },
      { type: 'mcq', question: 'What is the output of print(type(10))?', options: ["<class 'int'>", "<class 'float'>", "<class 'str'>", "<class 'num'>"], correct: 0 },
      { type: 'mcq', question: 'Which of the following is a valid variable name in Python?', options: ['2name', 'my-name', '_name', 'class'], correct: 2 },
      { type: 'mcq', question: 'Python is a _____ typed language.', options: ['Statically', 'Dynamically', 'Weakly', 'Manually'], correct: 1 },
      { type: 'short', question: 'What function is used to display output in Python?', answer: 'print' },
      { type: 'short', question: 'What symbol is used for single-line comments in Python?', answer: '#' },
      { type: 'short', question: 'What is the file extension for Python scripts?', answer: '.py' },
    ] as Question[],
    2: [
      { type: 'mcq', question: 'Which data type is immutable in Python?', options: ['list', 'dict', 'set', 'tuple'], correct: 3 },
      { type: 'mcq', question: 'What does int("42") return?', options: ['Error', '42', '"42"', 'None'], correct: 1 },
      { type: 'mcq', question: 'Which of the following is a float?', options: ['10', '"10.5"', '10.5', 'True'], correct: 2 },
      { type: 'mcq', question: 'What is the type of True in Python?', options: ['int', 'str', 'bool', 'float'], correct: 2 },
      { type: 'short', question: 'What built-in function converts a string to an integer?', answer: 'int' },
      { type: 'short', question: 'What is the boolean value of an empty string in Python?', answer: 'False' },
      { type: 'short', question: 'What keyword represents a null value in Python?', answer: 'None' },
    ] as Question[],
    3: [
      { type: 'mcq', question: 'What does the // operator do in Python?', options: ['Division', 'Floor division', 'Modulus', 'Power'], correct: 1 },
      { type: 'mcq', question: 'What is the result of 2 ** 3?', options: ['6', '8', '5', '9'], correct: 1 },
      { type: 'mcq', question: 'Which operator checks equality?', options: ['=', '==', '!=', ':='], correct: 1 },
      { type: 'mcq', question: 'What does the % operator return?', options: ['Quotient', 'Remainder', 'Product', 'Power'], correct: 1 },
      { type: 'short', question: 'What operator is used for exponentiation in Python?', answer: '**' },
      { type: 'short', question: 'What logical operator returns True if both conditions are True?', answer: 'and' },
      { type: 'short', question: 'What is 10 % 3?', answer: '1' },
    ] as Question[],
    4: [
      { type: 'mcq', question: 'Which method converts a string to uppercase?', options: ['upper()', 'toUpper()', 'capitalize()', 'UP()'], correct: 0 },
      { type: 'mcq', question: 'What does "hello"[1] return?', options: ['h', 'e', 'l', 'o'], correct: 1 },
      { type: 'mcq', question: 'Which method removes whitespace from both ends of a string?', options: ['trim()', 'strip()', 'clean()', 'cut()'], correct: 1 },
      { type: 'mcq', question: 'How do you concatenate two strings in Python?', options: ['&', '+', '.', ','], correct: 1 },
      { type: 'short', question: 'What method returns the length of a string?', answer: 'len' },
      { type: 'short', question: 'What does "abc".replace("a","x") return?', answer: 'xbc' },
      { type: 'short', question: 'Are strings mutable or immutable in Python?', answer: 'immutable' },
    ] as Question[],
    5: [
      { type: 'mcq', question: 'How do you create an empty list in Python?', options: ['list()', '[]', 'Both A and B', '{}'], correct: 2 },
      { type: 'mcq', question: 'What method adds an element to the end of a list?', options: ['add()', 'append()', 'insert()', 'push()'], correct: 1 },
      { type: 'mcq', question: 'What does [1,2,3][1:] return?', options: ['[1,2]', '[2,3]', '[1]', '[3]'], correct: 1 },
      { type: 'mcq', question: 'Which method sorts a list in place?', options: ['sorted()', 'sort()', 'order()', 'arrange()'], correct: 1 },
      { type: 'short', question: 'What method removes the last element from a list?', answer: 'pop' },
      { type: 'short', question: 'Are lists mutable or immutable?', answer: 'mutable' },
      { type: 'short', question: 'What function returns the number of items in a list?', answer: 'len' },
    ] as Question[],
    6: [
      { type: 'mcq', question: 'How do you create a tuple with one element?', options: ['(1)', '(1,)', '[1]', '{1}'], correct: 1 },
      { type: 'mcq', question: 'Which is true about tuples?', options: ['Mutable', 'Immutable', 'Unordered', 'No duplicates'], correct: 1 },
      { type: 'mcq', question: 'What does tuple unpacking do?', options: ['Converts to list', 'Assigns elements to variables', 'Sorts the tuple', 'Reverses the tuple'], correct: 1 },
      { type: 'mcq', question: 'Can a tuple contain different data types?', options: ['No', 'Yes', 'Only numbers', 'Only strings'], correct: 1 },
      { type: 'short', question: 'What built-in function converts a list to a tuple?', answer: 'tuple' },
      { type: 'short', question: 'What method counts occurrences of a value in a tuple?', answer: 'count' },
      { type: 'short', question: 'Can you modify a tuple after creation?', answer: 'no' },
    ] as Question[],
    7: [
      { type: 'mcq', question: 'How do you access a value in a dictionary?', options: ['dict[key]', 'dict.key', 'dict(key)', 'dict->key'], correct: 0 },
      { type: 'mcq', question: 'Which method returns all keys in a dictionary?', options: ['items()', 'values()', 'keys()', 'get()'], correct: 2 },
      { type: 'mcq', question: 'What happens if you access a non-existent key with dict[key]?', options: ['Returns None', 'Returns 0', 'KeyError', 'Returns False'], correct: 2 },
      { type: 'mcq', question: 'Which method safely gets a value with a default?', options: ['find()', 'get()', 'fetch()', 'retrieve()'], correct: 1 },
      { type: 'short', question: 'Are dictionary keys unique?', answer: 'yes' },
      { type: 'short', question: 'What method removes a key-value pair by key?', answer: 'pop' },
      { type: 'short', question: 'What symbol is used to define a dictionary?', answer: '{}' },
    ] as Question[],
  },
  intermediate: {
    1: [
      { type: 'mcq', question: 'Which keyword is used to define a function in Python?', options: ['func', 'function', 'def', 'define'], correct: 2 },
      { type: 'mcq', question: 'What does a function return if no return statement is specified?', options: ['0', 'False', 'None', 'Error'], correct: 2 },
      { type: 'mcq', question: 'What is a default parameter?', options: ['A required parameter', 'A parameter with a preset value', 'A global variable', 'A return value'], correct: 1 },
      { type: 'mcq', question: 'What does *args do in a function definition?', options: ['Creates a list', 'Accepts variable positional arguments', 'Creates a dictionary', 'Raises an error'], correct: 1 },
      { type: 'short', question: 'What keyword returns a value from a function?', answer: 'return' },
      { type: 'short', question: 'What is a function without a name called?', answer: 'lambda' },
      { type: 'short', question: 'What does **kwargs accept?', answer: 'keyword' },
    ] as Question[],
    2: [
      { type: 'mcq', question: 'Which keyword is used to import a module?', options: ['include', 'import', 'require', 'use'], correct: 1 },
      { type: 'mcq', question: 'What does "from math import sqrt" do?', options: ['Imports entire math module', 'Imports only sqrt function', 'Creates a new module', 'Raises an error'], correct: 1 },
      { type: 'mcq', question: 'Which file makes a directory a Python package?', options: ['main.py', '__init__.py', 'setup.py', 'module.py'], correct: 1 },
      { type: 'mcq', question: 'What does the os module provide?', options: ['Math functions', 'Operating system interface', 'Web requests', 'Data visualization'], correct: 1 },
      { type: 'short', question: 'What keyword gives a module an alias?', answer: 'as' },
      { type: 'short', question: 'What built-in module handles JSON data?', answer: 'json' },
      { type: 'short', question: 'What module provides random number generation?', answer: 'random' },
    ] as Question[],
    3: [
      { type: 'mcq', question: 'Which function opens a file in Python?', options: ['file()', 'open()', 'read()', 'load()'], correct: 1 },
      { type: 'mcq', question: 'What mode opens a file for writing (overwrite)?', options: ['"r"', '"w"', '"a"', '"x"'], correct: 1 },
      { type: 'mcq', question: 'What does the "with" statement do for files?', options: ['Opens files faster', 'Auto-closes the file', 'Encrypts the file', 'Compresses the file'], correct: 1 },
      { type: 'mcq', question: 'What method reads the entire file as a string?', options: ['readline()', 'readlines()', 'read()', 'readall()'], correct: 2 },
      { type: 'short', question: 'What mode opens a file for appending?', answer: 'a' },
      { type: 'short', question: 'What method writes a string to a file?', answer: 'write' },
      { type: 'short', question: 'What method reads one line at a time?', answer: 'readline' },
    ] as Question[],
    4: [
      { type: 'mcq', question: 'Which block handles exceptions in Python?', options: ['catch', 'except', 'handle', 'error'], correct: 1 },
      { type: 'mcq', question: 'What does the "finally" block do?', options: ['Catches errors', 'Always executes', 'Raises exceptions', 'Skips errors'], correct: 1 },
      { type: 'mcq', question: 'Which keyword raises an exception manually?', options: ['throw', 'raise', 'error', 'except'], correct: 1 },
      { type: 'mcq', question: 'What is the base class for all exceptions?', options: ['Error', 'Exception', 'BaseException', 'RuntimeError'], correct: 2 },
      { type: 'short', question: 'What keyword starts an exception handler?', answer: 'try' },
      { type: 'short', question: 'What exception is raised for division by zero?', answer: 'ZeroDivisionError' },
      { type: 'short', question: 'Can you have multiple except blocks?', answer: 'yes' },
    ] as Question[],
    5: [
      { type: 'mcq', question: 'Which keyword defines a class in Python?', options: ['struct', 'object', 'class', 'type'], correct: 2 },
      { type: 'mcq', question: 'What is the constructor method in Python?', options: ['__init__', '__new__', '__create__', '__start__'], correct: 0 },
      { type: 'mcq', question: 'What does "self" refer to?', options: ['The class', 'The current instance', 'The parent class', 'A global variable'], correct: 1 },
      { type: 'mcq', question: 'What is encapsulation?', options: ['Hiding implementation details', 'Creating subclasses', 'Overriding methods', 'Using modules'], correct: 0 },
      { type: 'short', question: 'What is a function inside a class called?', answer: 'method' },
      { type: 'short', question: 'What is creating an object from a class called?', answer: 'instantiation' },
      { type: 'short', question: 'What prefix makes an attribute private by convention?', answer: '_' },
    ] as Question[],
    6: [
      { type: 'mcq', question: 'What does inheritance allow?', options: ['Code duplication', 'Reusing code from parent class', 'Hiding variables', 'Error handling'], correct: 1 },
      { type: 'mcq', question: 'How do you call the parent class constructor?', options: ['parent()', 'super().__init__()', 'base()', 'this()'], correct: 1 },
      { type: 'mcq', question: 'Does Python support multiple inheritance?', options: ['No', 'Yes', 'Only with modules', 'Only in Python 3'], correct: 1 },
      { type: 'mcq', question: 'What is method overriding?', options: ['Deleting a method', 'Redefining a parent method in child', 'Creating a new method', 'Calling super()'], correct: 1 },
      { type: 'short', question: 'What function checks if an object is an instance of a class?', answer: 'isinstance' },
      { type: 'short', question: 'What is the order in which Python resolves methods called?', answer: 'MRO' },
      { type: 'short', question: 'What keyword is used to inherit from a parent class?', answer: 'class' },
    ] as Question[],
    7: [
      { type: 'mcq', question: 'What is a decorator in Python?', options: ['A loop construct', 'A function that modifies another function', 'A class method', 'An exception handler'], correct: 1 },
      { type: 'mcq', question: 'What symbol is used before a decorator?', options: ['#', '@', '!', '$'], correct: 1 },
      { type: 'mcq', question: 'Which built-in decorator makes a method static?', options: ['@classmethod', '@staticmethod', '@property', '@abstract'], correct: 1 },
      { type: 'mcq', question: 'What does @property do?', options: ['Makes a method callable as attribute', 'Creates a class variable', 'Deletes an attribute', 'Raises an error'], correct: 0 },
      { type: 'short', question: 'Can decorators be stacked on a single function?', answer: 'yes' },
      { type: 'short', question: 'What module provides functools.wraps for decorators?', answer: 'functools' },
      { type: 'short', question: 'What does @classmethod receive as first argument?', answer: 'cls' },
    ] as Question[],
  },
  advanced: {
    1: [
      { type: 'mcq', question: 'What keyword is used to create a generator?', options: ['return', 'yield', 'generate', 'async'], correct: 1 },
      { type: 'mcq', question: 'What does a generator return?', options: ['A list', 'An iterator', 'A tuple', 'A dictionary'], correct: 1 },
      { type: 'mcq', question: 'What is the advantage of generators over lists?', options: ['Faster indexing', 'Memory efficiency', 'Type safety', 'Thread safety'], correct: 1 },
      { type: 'mcq', question: 'What function advances a generator?', options: ['advance()', 'next()', 'step()', 'continue()'], correct: 1 },
      { type: 'short', question: 'What exception is raised when a generator is exhausted?', answer: 'StopIteration' },
      { type: 'short', question: 'Can generator expressions use parentheses?', answer: 'yes' },
      { type: 'short', question: 'What keyword pauses a generator and returns a value?', answer: 'yield' },
    ] as Question[],
    2: [
      { type: 'mcq', question: 'Which keyword defines an async function?', options: ['async', 'await', 'defer', 'promise'], correct: 0 },
      { type: 'mcq', question: 'What does "await" do?', options: ['Creates a thread', 'Pauses until the coroutine completes', 'Raises an error', 'Cancels a task'], correct: 1 },
      { type: 'mcq', question: 'Which module provides the event loop?', options: ['threading', 'asyncio', 'concurrent', 'multiprocessing'], correct: 1 },
      { type: 'mcq', question: 'What is a coroutine?', options: ['A regular function', 'An async function that can be paused', 'A thread', 'A process'], correct: 1 },
      { type: 'short', question: 'What method runs the async event loop?', answer: 'run' },
      { type: 'short', question: 'Can you use await outside an async function?', answer: 'no' },
      { type: 'short', question: 'What does asyncio.gather() do?', answer: 'concurrency' },
    ] as Question[],
    3: [
      { type: 'mcq', question: 'What is a metaclass?', options: ['A subclass', 'A class of a class', 'A decorator', 'An abstract class'], correct: 1 },
      { type: 'mcq', question: 'What is the default metaclass in Python?', options: ['object', 'type', 'meta', 'base'], correct: 1 },
      { type: 'mcq', question: 'Which method controls class creation in a metaclass?', options: ['__init__', '__new__', '__create__', '__build__'], correct: 1 },
      { type: 'mcq', question: 'When are metaclasses useful?', options: ['For simple scripts', 'For frameworks and ORMs', 'For loops', 'For file handling'], correct: 1 },
      { type: 'short', question: 'What keyword sets a metaclass for a class?', answer: 'metaclass' },
      { type: 'short', question: 'What function returns the type of an object?', answer: 'type' },
      { type: 'short', question: 'Are metaclasses commonly used in everyday Python?', answer: 'no' },
    ] as Question[],
    4: [
      { type: 'mcq', question: 'What does a context manager handle?', options: ['Loops', 'Resource management', 'Type checking', 'Sorting'], correct: 1 },
      { type: 'mcq', question: 'Which methods must a context manager implement?', options: ['open/close', '__enter__/__exit__', 'start/stop', 'begin/end'], correct: 1 },
      { type: 'mcq', question: 'What module provides @contextmanager?', options: ['os', 'sys', 'contextlib', 'functools'], correct: 2 },
      { type: 'mcq', question: 'What keyword uses a context manager?', options: ['using', 'with', 'context', 'manage'], correct: 1 },
      { type: 'short', question: 'What method is called when entering a with block?', answer: '__enter__' },
      { type: 'short', question: 'What method is called when exiting a with block?', answer: '__exit__' },
      { type: 'short', question: 'Can context managers suppress exceptions?', answer: 'yes' },
    ] as Question[],
    5: [
      { type: 'mcq', question: 'Which module provides threading in Python?', options: ['thread', 'threading', 'multithread', 'concurrent'], correct: 1 },
      { type: 'mcq', question: 'What is the GIL?', options: ['A threading library', 'Global Interpreter Lock', 'A debugging tool', 'A memory manager'], correct: 1 },
      { type: 'mcq', question: 'Does the GIL allow true parallelism for CPU-bound tasks?', options: ['Yes', 'No', 'Only in Python 2', 'Only on Linux'], correct: 1 },
      { type: 'mcq', question: 'What method starts a thread?', options: ['run()', 'start()', 'begin()', 'execute()'], correct: 1 },
      { type: 'short', question: 'What is a race condition?', answer: 'conflict' },
      { type: 'short', question: 'What synchronization primitive prevents simultaneous access?', answer: 'Lock' },
      { type: 'short', question: 'What method waits for a thread to finish?', answer: 'join' },
    ] as Question[],
    6: [
      { type: 'mcq', question: 'What module provides process-based parallelism?', options: ['threading', 'multiprocessing', 'asyncio', 'subprocess'], correct: 1 },
      { type: 'mcq', question: 'What is the advantage of multiprocessing over threading?', options: ['Simpler code', 'Bypasses the GIL', 'Uses less memory', 'Faster startup'], correct: 1 },
      { type: 'mcq', question: 'What class creates a pool of worker processes?', options: ['ThreadPool', 'Pool', 'Workers', 'Executor'], correct: 1 },
      { type: 'mcq', question: 'How do processes communicate?', options: ['Global variables', 'Queue or Pipe', 'Direct memory', 'Decorators'], correct: 1 },
      { type: 'short', question: 'What module combines threads and processes under one API?', answer: 'concurrent' },
      { type: 'short', question: 'Can multiprocessing share memory between processes?', answer: 'yes' },
      { type: 'short', question: 'What class provides shared state between processes?', answer: 'Manager' },
    ] as Question[],
    7: [
      { type: 'mcq', question: 'What is the Singleton design pattern?', options: ['Multiple instances', 'Only one instance of a class', 'A factory method', 'An observer'], correct: 1 },
      { type: 'mcq', question: 'Which pattern creates objects without specifying exact class?', options: ['Singleton', 'Factory', 'Observer', 'Strategy'], correct: 1 },
      { type: 'mcq', question: 'What does the Observer pattern do?', options: ['Creates objects', 'Notifies dependents of state changes', 'Manages memory', 'Sorts data'], correct: 1 },
      { type: 'mcq', question: 'Which pattern defines a family of interchangeable algorithms?', options: ['Factory', 'Singleton', 'Strategy', 'Decorator'], correct: 2 },
      { type: 'short', question: 'What pattern adds behavior to objects dynamically?', answer: 'decorator' },
      { type: 'short', question: 'What pattern provides a simplified interface to a complex system?', answer: 'facade' },
      { type: 'short', question: 'What are design patterns?', answer: 'solutions' },
    ] as Question[],
  },
};

export default pythonQuestions;
